"""
Pydantic Schemas Package

This package contains all Pydantic models for API request/response validation.
Organized by domain for better maintainability.
"""

# User schemas
from app.schemas.user import (
    AgeGroup,
    LearningLevel,
    UserRole,
    UserCreate,
    UserLogin,
    UserUpdate,
    PasswordChange,
    UserResponse,
    UserProfile,
    UserLoginResponse,
    UserRegistrationResponse,
    UserStatistics,
    TokenRefresh,
    TokenResponse,
)

# GSL schemas
from app.schemas.gsl import (
    SignCategory,
    DifficultyLevel,
    RecognitionStatus,
    TranslationType,
    SignRecognitionRequest,
    GestureValidationRequest,
    SpeechToSignRequest,
    TextToSignRequest,
    SignToTextRequest,
    DictionarySearchRequest,
    SignCreateRequest,
    GSLSignResponse,
    SignRecognitionResponse,
    GestureValidationResponse,
    TranslationResponse,
    SignSequenceResponse,
    DictionarySearchResponse,
    BatchRecognitionRequest,
    BatchRecognitionResponse,
)

# Learning schemas
from app.schemas.learning import (
    LessonLevel,
    LessonCategory,
    ExerciseType,
    AchievementType,
    PracticeSessionType,
    LessonSearchRequest,
    LessonProgressUpdate,
    PracticeSessionCreate,
    ExerciseSubmission,
    QuizSubmission,
    LessonCreateRequest,
    ExerciseResponse,
    LessonResponse,
    LessonProgressResponse,
    AchievementResponse,
    PracticeSessionResponse,
    QuizResponse,
    QuizResultResponse,
    LearningAnalytics,
    ProgressSummary,
)

# Common schemas
from app.schemas.common import (
    StatusEnum,
    ErrorCode,
    PaginationParams,
    PaginationMeta,
    PaginatedResponse,
    ErrorDetail,
    ErrorResponse,
    SuccessResponse,
    HealthCheckResponse,
    FileUploadResponse,
    BulkOperationRequest,
    BulkOperationResponse,
    SearchRequest,
    SearchResponse,
    RateLimitInfo,
    MetadataResponse,
    BatchRequest,
    BatchResponse,
)

# Media schemas
from app.schemas.media import (
    MediaType,
    VideoFormat,
    ImageFormat,
    AudioFormat,
    ProcessingStatus,
    MediaQuality,
    MediaUploadRequest,
    VideoUploadRequest,
    ImageUploadRequest,
    AudioUploadRequest,
    MediaProcessingRequest,
    VideoTrimRequest,
    ImageResizeRequest,
    ThumbnailGenerateRequest,
    MediaResponse,
    VideoResponse,
    ImageResponse,
    AudioResponse,
    MediaProcessingResponse,
    MediaListResponse,
    MediaUploadUrlResponse,
    MediaAnalysisResponse,
    MediaStatistics,
)

# Analytics schemas
from app.schemas.analytics import (
    TimeRange,
    MetricType,
    AggregationType,
    ChartType,
    AnalyticsRequest,
    UserAnalyticsRequest,
    LessonAnalyticsRequest,
    SignRecognitionAnalyticsRequest,
    DataPoint,
    MetricSummary,
    AnalyticsResponse,
    UserEngagementMetrics,
    LearningProgressMetrics,
    SignRecognitionMetrics,
    LessonCompletionMetrics,
    SystemPerformanceMetrics,
    DashboardMetrics,
    TrendAnalysis,
    ComparisonReport,
    ExportRequest,
    ExportResponse,
    InsightResponse,
)

__all__ = [
    # User
    "AgeGroup",
    "LearningLevel",
    "UserRole",
    "UserCreate",
    "UserLogin",
    "UserUpdate",
    "PasswordChange",
    "UserResponse",
    "UserProfile",
    "UserLoginResponse",
    "UserRegistrationResponse",
    "UserStatistics",
    "TokenRefresh",
    "TokenResponse",
    # GSL
    "SignCategory",
    "DifficultyLevel",
    "RecognitionStatus",
    "TranslationType",
    "SignRecognitionRequest",
    "GestureValidationRequest",
    "SpeechToSignRequest",
    "TextToSignRequest",
    "SignToTextRequest",
    "DictionarySearchRequest",
    "SignCreateRequest",
    "GSLSignResponse",
    "SignRecognitionResponse",
    "GestureValidationResponse",
    "TranslationResponse",
    "SignSequenceResponse",
    "DictionarySearchResponse",
    "BatchRecognitionRequest",
    "BatchRecognitionResponse",
    # Learning
    "LessonLevel",
    "LessonCategory",
    "ExerciseType",
    "AchievementType",
    "PracticeSessionType",
    "LessonSearchRequest",
    "LessonProgressUpdate",
    "PracticeSessionCreate",
    "ExerciseSubmission",
    "QuizSubmission",
    "LessonCreateRequest",
    "ExerciseResponse",
    "LessonResponse",
    "LessonProgressResponse",
    "AchievementResponse",
    "PracticeSessionResponse",
    "QuizResponse",
    "QuizResultResponse",
    "LearningAnalytics",
    "ProgressSummary",
    # Common
    "StatusEnum",
    "ErrorCode",
    "PaginationParams",
    "PaginationMeta",
    "PaginatedResponse",
    "ErrorDetail",
    "ErrorResponse",
    "SuccessResponse",
    "HealthCheckResponse",
    "FileUploadResponse",
    "BulkOperationRequest",
    "BulkOperationResponse",
    "SearchRequest",
    "SearchResponse",
    "RateLimitInfo",
    "MetadataResponse",
    "BatchRequest",
    "BatchResponse",
    # Media
    "MediaType",
    "VideoFormat",
    "ImageFormat",
    "AudioFormat",
    "ProcessingStatus",
    "MediaQuality",
    "MediaUploadRequest",
    "VideoUploadRequest",
    "ImageUploadRequest",
    "AudioUploadRequest",
    "MediaProcessingRequest",
    "VideoTrimRequest",
    "ImageResizeRequest",
    "ThumbnailGenerateRequest",
    "MediaResponse",
    "VideoResponse",
    "ImageResponse",
    "AudioResponse",
    "MediaProcessingResponse",
    "MediaListResponse",
    "MediaUploadUrlResponse",
    "MediaAnalysisResponse",
    "MediaStatistics",
    # Analytics
    "TimeRange",
    "MetricType",
    "AggregationType",
    "ChartType",
    "AnalyticsRequest",
    "UserAnalyticsRequest",
    "LessonAnalyticsRequest",
    "SignRecognitionAnalyticsRequest",
    "DataPoint",
    "MetricSummary",
    "AnalyticsResponse",
    "UserEngagementMetrics",
    "LearningProgressMetrics",
    "SignRecognitionMetrics",
    "LessonCompletionMetrics",
    "SystemPerformanceMetrics",
    "DashboardMetrics",
    "TrendAnalysis",
    "ComparisonReport",
    "ExportRequest",
    "ExportResponse",
    "InsightResponse",
]
